version: '3'
networks:
    selenoid:
        external:
            name: selenoid
services:
    hub:
        image: "selenoid/hub"
        networks:
            selenoid: null
        volumes:
            - "$PWD/selenoid/config/:/etc/selenoid/:ro"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "$PWD/selenoid/video/:/opt/selenoid/video"
            - "$PWD/selenoid/logs/:/opt/selenoid/logs"
        environment:
            - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video/
        command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "4", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]
    selenoid-ui:
        image: "aerokube/selenoid-ui"
        networks:
            selenoid: null
        ports:
            - "80:8080"
        command: ["--selenoid-uri", "http://hub:4444"]
